### ISSUE TITLE
Cannot pass input file if isTTY is false

### ISSUE THREAD

**Issue by timocov** [shashkovdanil/clean-publish#51]
I'm not sure about that and don't really understand what isTTY property stands for, but it looks like it might be `false` even if no data provided in stdin - I've tested in github actions, and it fails with error
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/home/runner/work/dts-bundle-generator/dts-bundle-generator/node_modules/clean-publish/utils.js:43:29)
    at Socket.emit (events.js:328:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`
```

https://github.com/shashkovdanil/clean-publish/blob/aaafdd4407c0d78608c1f10b196a8cfe9559feeb/clear-package-json.js#L59-L61

Related to https://github.com/actions/runner/issues/241

**Comment by ai** [comment]
Fixed in https://github.com/shashkovdanil/clean-publish/pull/84
